services:
  jenkins:
    build: .
    privileged: true
    user: root
    ports:
    - 8083:8083
    - 50000:50000
    container_name: jenkins
    volumes:
    - /workspaces/ensf400-lab9-jenkins/jenkins_home:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
